language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev rpm
  - if [ "$CC" = "gcc" ]; then sudo apt-get install -qq gcc-4.8; fi

before_script:
    # force newer gcc version
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi
    # show which tests failed
  - export CTEST_OUTPUT_ON_FAILURE=1
    # pull all sub modules recursively
  - git submodule update --init --recursive

script:
  - cmake .
  - make -j2
  - make test
before_deploy:
  - "cd ./src && sudo make package"
  - "sudo chown $USER $TRAVIS_BUILD_DIR/C-Dogs*SDL-*-Linux.*"
deploy:
  provider: releases
  api_key:
    secure: 59BXlwvCT1GMuMrx5yf9TjD6BsXbxxC/lAB7ry7sFMdKmNg8v9vs9lH8g31XF2BPPDaH1sepJjRhn0qHciikQJ3X+ZbN2YpFF6KNKp/FOw3ytx/8SDiWO2BzqVnstE+XihRdki+oR2ntPFKhEMhWsRlS2o9JY+g9pT+0BLtqp4I=
  file:
    - "$TRAVIS_BUILD_DIR/C-Dogs*SDL-*-Linux.deb"
    - "$TRAVIS_BUILD_DIR/C-Dogs*SDL-*-Linux.tar.gz"
    - "$TRAVIS_BUILD_DIR/C-Dogs*SDL-*-Linux.rpm"
  skip_cleanup: true
  on:
    tags: true
    condition: $CC = gcc-4.8
