sudo: false

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - rpm
    - ia32-libs-sdl

before_install:
  - bash build/travis-ci/install-sdl2.sh
install:
  # SDL2
  - export SDL_PREFIX=$HOME/sdl2
  - export PKG_CONFIG_PATH=$SDL_PREFIX/lib/pkgconfig
  - export PATH=$PATH:$SDL_PREFIX/bin/
cache:
  directories:
  - $HOME/sdl2
before_script:
    # force newer gcc version
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi
    # show which tests failed
  - export CTEST_OUTPUT_ON_FAILURE=1
    # pull all sub modules recursively
  - git submodule update --init --recursive

script:
  - cmake -DCMAKE_INSTALL_PREFIX=. .
  - make -j2
  - make test
before_deploy:
  - make package
deploy:
  provider: releases
  api_key:
    secure: Rus8lTl0EnVqM6PXwleQ8cffjMTMY1gHGwVdbGsu8cWaDgAWQ86TFgGBbV+x12z9floDPzI7Z1K/entktkiSWQyRPIa9jQfJBIomNABhIykUvpRsL026Cs8TysI4L4hrTvFev10QI28RFyZvUDBT8yytowFsuU5Pfb4n7kDIisQ=
  file_glob: true
  file:
    - "$TRAVIS_BUILD_DIR/C-Dogs*SDL-*-Linux.tar.gz"
  skip_cleanup: true
  on:
    tags: true
    condition: $CC = gcc-4.8
