language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev rpm
  - if [ "$CC" = "gcc" ]; then sudo apt-get install -qq gcc-4.8; fi

before_script:
    # force newer gcc version
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi
    # show which tests failed
  - export CTEST_OUTPUT_ON_FAILURE=1
    # pull all sub modules recursively
  - git submodule update --init --recursive

script:
  - cmake .
  - make -j2
  - make test
before_deploy:
  - "cd ./src && sudo make package"
  - "sudo chown $USER $TRAVIS_BUILD_DIR/C-Dogs*SDL-*-Linux.*"
deploy:
  provider: releases
  api_key:
    secure: cJSUi9wKAjJ7LqPQ8UXnMfHoDYwow4lHqQnp+EGAle1BHrbwMYPinfQzzLXRy40rqFrF2b/t0qBsGNJRNGBhI65nSgJElLGsgyAkV3h31uvVop5T4f93eEcuFMPYG74UtUPwTPTmRLB1GxZumELvKgJyne7xF4JHTvUDlsQAqg0=
  file:
    - "$TRAVIS_BUILD_DIR/C-Dogs SDL-$TRAVIS_TAG-Linux.deb"
    - "$TRAVIS_BUILD_DIR/C-Dogs SDL-$TRAVIS_TAG-Linux.tar.gz"
    - "$TRAVIS_BUILD_DIR/C-Dogs-SDL-$TRAVIS_TAG-Linux.rpm"
  skip_cleanup: true
  on:
    tags: true
    condition: $CC = gcc
