language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - gcc-multilib
    - libstdc++6:i386
    - libc6:i386
    - rpm

before_install:
  - bash build/travis-ci/install-sdl2.sh
cache:
  directories:
  - /opt/gcw0-toolchain
before_script:
    # force newer gcc version
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi
    # show which tests failed
  - export CTEST_OUTPUT_ON_FAILURE=1

script:
  - cmake .
  - make -j2
  - make test
before_deploy:
  - sudo make package
  - "sudo chown $USER $TRAVIS_BUILD_DIR/C-Dogs*SDL-*-Linux.*"
  # GCW-Zero
  - bash build/travis-ci/install-gcw0-toolchain.sh
  - sh make_gcw0.sh
deploy:
  provider: releases
  api_key:
    secure: Rus8lTl0EnVqM6PXwleQ8cffjMTMY1gHGwVdbGsu8cWaDgAWQ86TFgGBbV+x12z9floDPzI7Z1K/entktkiSWQyRPIa9jQfJBIomNABhIykUvpRsL026Cs8TysI4L4hrTvFev10QI28RFyZvUDBT8yytowFsuU5Pfb4n7kDIisQ=
  file_glob: true
  file:
    - "$TRAVIS_BUILD_DIR/C-Dogs*SDL-*-Linux.tar.gz"
    - "$TRAVIS_BUILD_DIR/gcw0build/cdogs-sdl.opk"
  skip_cleanup: true
  on:
    tags: true
    condition: $CC = gcc-4.8
