language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq

install:
  - if [ "$CC" = "gcc" ]; then sudo apt-get install -qq gcc-4.8; fi
  # SDL2
  - curl -O http://www.libsdl.org/release/SDL2-2.0.3.tar.gz
  - tar -xzvf SDL2-2.0.3.tar.gz
  - (cd SDL2-2.0.3 && ./configure && make && sudo make install)
  - curl -O https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.0.tar.gz
  - tar -xzvf SDL2_image-2.0.0.tar.gz
  - (cd SDL2_image-2.0.0 && ./configure && make && sudo make install)
  - curl -O https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.0.tar.gz
  - tar -xzvf SDL2_mixer-2.0.0.tar.gz
  - (cd SDL2_mixer-2.0.0 && ./configure && make && sudo make install)
before_script:
    # force newer gcc version
  - if [ "$CC" = "gcc" ]; then export CC="gcc-4.8"; fi
    # show which tests failed
  - export CTEST_OUTPUT_ON_FAILURE=1
    # pull all sub modules recursively
  - git submodule update --init --recursive

script:
  - cmake .
  - make -j2
  - make test
before_deploy:
  - "cd ./src && sudo make package"
  - "sudo chown $USER $TRAVIS_BUILD_DIR/C-Dogs*SDL-*-Linux.*"
deploy:
  provider: releases
  api_key:
    secure: Rus8lTl0EnVqM6PXwleQ8cffjMTMY1gHGwVdbGsu8cWaDgAWQ86TFgGBbV+x12z9floDPzI7Z1K/entktkiSWQyRPIa9jQfJBIomNABhIykUvpRsL026Cs8TysI4L4hrTvFev10QI28RFyZvUDBT8yytowFsuU5Pfb4n7kDIisQ=
  file_glob: true
  file:
    - "$TRAVIS_BUILD_DIR/C-Dogs*SDL-*-Linux.tar.gz"
  skip_cleanup: true
  on:
    tags: true
    condition: $CC = gcc-4.8
