language: c
dist: bionic
osx_image: xcode10.3

compiler:
  - gcc
  - clang
os:
  - linux
  - osx

env:
  - CCACHE_CPP2=yes

sudo: required

cache: ccache

addons:
  apt:
    packages:
    - rpm
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-mixer-dev
    - clang-9
    - cmake
    - gcc-9
    - ninja-build

before_script:
  - export CTEST_OUTPUT_ON_FAILURE=1

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh build/macosx/install-sdl2.sh ; fi
  # Match install prefix with data dir so that package contains everything required
  - cmake -DCMAKE_INSTALL_PREFIX=. -DDATA_INSTALL_DIR=. -Wno-dev .
  - make -j2

  # Tests are broken on osx. Hope this will be fixed some day
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make test ; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - make package

  #debug
  - ls $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  api_key:
    secure: Rus8lTl0EnVqM6PXwleQ8cffjMTMY1gHGwVdbGsu8cWaDgAWQ86TFgGBbV+x12z9floDPzI7Z1K/entktkiSWQyRPIa9jQfJBIomNABhIykUvpRsL026Cs8TysI4L4hrTvFev10QI28RFyZvUDBT8yytowFsuU5Pfb4n7kDIisQ=
  file_glob: true
  skip_cleanup: true
  file:
    - "$TRAVIS_BUILD_DIR/C-Dogs*SDL-*-{Linux,OSX}.{tar.gz,dmg}"
  on:
    tags: true
    condition: $CC = gcc
